### ISSUE TITLE
App has no feature to go back to main page

### ISSUE THREAD

**Issue by savioxavier** [JeswinSunsi/PentyDesktopAssistant#4]
I just looked at the app and found that there is no link (or perhaps, a button) that allows you to go back where you came from. You're stuck in the send mail webpage with no option to go back to title screen but to hit Alt+Left (in Windows)

You could add a button that always stays at the top-left with the following code:

HTML:
```
<button id="go-back" onclick="history.back()">
    <img src="img_back.png" alt="Go back">
</button>
``` 
CSS:
```
#go-back {
    /* Adjust values as required */
    position: fixed;
    top: 2%;
    left: 3%;
    /* Add your own code for styling below*/
}
```

**Comment by JeswinSunsi** [comment]
Hey Savio,
I did know of this and purposely reused the send button as the cancel button. If you have no content and recipient address, it cancels when you click the button. However, it was a quick fix and I'm going to add another button soon.
Thanxx
